name: netflix_clone
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.3
  google_fonts: ^2.0.0
  sliver_stretch_header: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/profil/
    - assets/others/
