var family = [
  {
    "genre_ids": [28, 35, 10751],
    "title": "Tom & Jerry",
    "original_language": "en",
    "original_title": "Tom & Jerry",
    "poster_path": "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
    "video": false,
    "vote_average": 7.4,
    "overview":
        "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
    "release_date": "2021-02-11",
    "vote_count": 1028,
    "id": 587807,
    "adult": false,
    "backdrop_path": "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
    "popularity": 1681.653,
    "media_type": "movie"
  },
  {
    "vote_average": 8.3,
    "overview":
        "After encounters with a dragon and a princess on her own mission, a Dragon Knight becomes embroiled in events larger than he could have ever imagined.",
    "id": 118956,
    "vote_count": 22,
    "backdrop_path": "/ifGVUbvl36CnY9mp4kquK8In1Rh.jpg",
    "name": "DOTA: Dragon's Blood",
    "genre_ids": [10759, 16, 10765],
    "origin_country": ["US"],
    "original_language": "en",
    "original_name": "DOTA: Dragon's Blood",
    "poster_path": "/s1wP1YeQS9fgSHiXZ3yJb2ufB2D.jpg",
    "first_air_date": "2021-03-25",
    "popularity": 249.304,
    "media_type": "tv"
  },
  {
    "adult": false,
    "backdrop_path": "/abCn6fJjCPEZE3Q2dCmfidMxrEG.jpg",
    "genre_ids": [18, 53, 80],
    "id": 596161,
    "original_language": "en",
    "original_title": "Let Him Go",
    "overview":
        "Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.",
    "poster_path": "/EsLZoT8oHhQlGd1QpdbnvnwTzO.jpg",
    "release_date": "2020-11-05",
    "title": "Let Him Go",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 212,
    "popularity": 49.866,
    "media_type": "movie"
  },
  {
    "backdrop_path": "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
    "first_air_date": "2021-03-26",
    "genre_ids": [16, 10759, 18],
    "id": 95557,
    "name": "Invincible",
    "origin_country": ["US"],
    "original_language": "en",
    "original_name": "Invincible",
    "overview":
        "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
    "poster_path": "/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
    "vote_average": 9.2,
    "vote_count": 93,
    "popularity": 199.151,
    "media_type": "tv"
  },
  {
    "release_date": "2021-03-26",
    "adult": false,
    "backdrop_path": "/sA07ynKTNXW2UMMOgPfLmFmmjgm.jpg",
    "genre_ids": [18, 10751, 10402, 10749],
    "vote_count": 68,
    "original_language": "en",
    "original_title": "A Week Away",
    "poster_path": "/htTS07IvYv3rv57ftzNEprefwSq.jpg",
    "title": "A Week Away",
    "video": false,
    "vote_average": 7.2,
    "id": 699102,
    "overview":
        "Troubled teen Will Hawkins has a run-in with the law that puts him at an important crossroad: go to juvenile detention or attend a Christian summer camp. At first a fish-out-of-water, Will opens his heart, discovers love with a camp regular, and sense of belonging in the last place he expected to find it.",
    "popularity": 290.532,
    "media_type": "movie"
  },
  {
    "overview":
        "Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.",
    "first_air_date": "2020-05-17",
    "id": 79680,
    "vote_count": 577,
    "genre_ids": [10765],
    "original_language": "en",
    "original_name": "Snowpiercer",
    "origin_country": ["US"],
    "name": "Snowpiercer",
    "poster_path": "/95xQPSqwvQDRoB3rXUn4lRyJrBW.jpg",
    "backdrop_path": "/2fhU42I8pPdvEKfrZtuJ8KrzdeF.jpg",
    "vote_average": 7.4,
    "popularity": 311.105,
    "media_type": "tv"
  },
  {
    "video": false,
    "vote_average": 8.3,
    "overview":
        "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
    "release_date": "2020-12-25",
    "title": "Soul",
    "adult": false,
    "backdrop_path": "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
    "id": 508442,
    "genre_ids": [10751, 16, 35, 18, 10402, 14],
    "vote_count": 5486,
    "original_language": "en",
    "original_title": "Soul",
    "poster_path": "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
    "popularity": 738.359,
    "media_type": "movie"
  }
];
