var personalFilms = [
  {
    "backdrop_path": "/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg",
    "genre_ids": [16, 12, 14, 10751, 28],
    "original_language": "en",
    "original_title": "Raya and the Last Dragon",
    "poster_path": "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
    "video": false,
    "vote_average": 8.3,
    "vote_count": 1842,
    "overview":
        "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
    "release_date": "2021-03-03",
    "title": "Raya and the Last Dragon",
    "id": 527774,
    "adult": false,
    "popularity": 2693.845,
    "media_type": "movie"
  },
  {
    "video": false,
    "vote_average": 6.1,
    "title": "Bad Trip",
    "vote_count": 47,
    "overview":
        "Two pals embark on a road trip full of funny pranks that pull real people into mayhem.",
    "adult": false,
    "backdrop_path": "/mtwThSQ8AJ2hV5KkVsDETgZISAw.jpg",
    "id": 578908,
    "genre_ids": [35],
    "release_date": "2021-03-26",
    "original_language": "en",
    "original_title": "Bad Trip",
    "poster_path": "/A1Gy5HX3DKGaNW1Ay30NTIVJqJ6.jpg",
    "popularity": 72.387,
    "media_type": "movie"
  },
  {
    "name": "Supergirl",
    "backdrop_path": "/jgb9xICHFX8wTGQ75js4uNbttQs.jpg",
    "genre_ids": [18, 10765, 10759],
    "id": 62688,
    "original_language": "en",
    "poster_path": "/zsaiq8ZclPuneuN7loLEbsh1ANJ.jpg",
    "vote_count": 2877,
    "vote_average": 7.2,
    "original_name": "Supergirl",
    "origin_country": ["US"],
    "overview":
        "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    "first_air_date": "2015-10-26",
    "popularity": 214.249,
    "media_type": "tv"
  },
  {
    "vote_average": 8.7,
    "overview":
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
    "vote_count": 3114,
    "poster_path": "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
    "first_air_date": "2013-04-07",
    "backdrop_path": "/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg",
    "name": "Attack on Titan",
    "genre_ids": [10765, 16, 10759],
    "id": 1429,
    "original_language": "ja",
    "original_name": "進撃の巨人",
    "origin_country": ["JP"],
    "popularity": 295.531,
    "media_type": "tv"
  },
  {
    "overview":
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
    "release_date": "2020-11-25",
    "id": 529203,
    "adult": false,
    "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
    "genre_ids": [10751, 14, 16, 35],
    "original_language": "en",
    "original_title": "The Croods: A New Age",
    "poster_path": "/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg",
    "title": "The Croods: A New Age",
    "video": false,
    "vote_average": 7.5,
    "vote_count": 1842,
    "popularity": 759.13,
    "media_type": "movie"
  },
  {
    "release_date": "2021-03-18",
    "adult": false,
    "backdrop_path": "/tzJZaglq1hR7RS35BKG68Xz7KY0.jpg",
    "genre_ids": [16, 35, 14],
    "vote_count": 40,
    "original_language": "ru",
    "original_title": "Ганзель, Гретель и Агентство Магии",
    "poster_path": "/4ZSzEDVdxWVMVO4oZDvoodQOEfr.jpg",
    "title": "Secret Magic Control Agency",
    "video": false,
    "vote_average": 7.7,
    "id": 797394,
    "overview":
        "The Secret Magic Control Agency sends its two best agents, Hansel and Gretel, to fight against the witch of the Gingerbread House.",
    "popularity": 67.939,
    "media_type": "movie"
  },
  {
    "adult": false,
    "backdrop_path": "/91nMJISKO8KqhTaYFMj6xFqI3GZ.jpg",
    "genre_ids": [18, 80, 9648, 53],
    "id": 567797,
    "original_language": "en",
    "original_title": "The Dry",
    "overview":
        "Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.",
    "poster_path": "/9tedVhYeK7fUqgwrjQAVw7RcI5d.jpg",
    "release_date": "2021-01-01",
    "title": "The Dry",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 10,
    "popularity": 4.091,
    "media_type": "movie"
  },
  {
    "genre_ids": [28, 35, 10751],
    "title": "Tom & Jerry",
    "original_language": "en",
    "original_title": "Tom & Jerry",
    "poster_path": "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
    "video": false,
    "vote_average": 7.4,
    "overview":
        "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
    "release_date": "2021-02-11",
    "vote_count": 1028,
    "id": 587807,
    "adult": false,
    "backdrop_path": "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
    "popularity": 1681.653,
    "media_type": "movie"
  },
  {
    "backdrop_path": "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
    "first_air_date": "2021-03-26",
    "genre_ids": [16, 10759, 18],
    "id": 95557,
    "name": "Invincible",
    "origin_country": ["US"],
    "original_language": "en",
    "original_name": "Invincible",
    "overview":
        "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
    "poster_path": "/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
    "vote_average": 9.2,
    "vote_count": 93,
    "popularity": 199.151,
    "media_type": "tv"
  },
  {
    "release_date": "2021-03-26",
    "adult": false,
    "backdrop_path": "/sA07ynKTNXW2UMMOgPfLmFmmjgm.jpg",
    "genre_ids": [18, 10751, 10402, 10749],
    "vote_count": 68,
    "original_language": "en",
    "original_title": "A Week Away",
    "poster_path": "/htTS07IvYv3rv57ftzNEprefwSq.jpg",
    "title": "A Week Away",
    "video": false,
    "vote_average": 7.2,
    "id": 699102,
    "overview":
        "Troubled teen Will Hawkins has a run-in with the law that puts him at an important crossroad: go to juvenile detention or attend a Christian summer camp. At first a fish-out-of-water, Will opens his heart, discovers love with a camp regular, and sense of belonging in the last place he expected to find it.",
    "popularity": 290.532,
    "media_type": "movie"
  },
  {
    "overview":
        "Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.",
    "first_air_date": "2020-05-17",
    "id": 79680,
    "vote_count": 577,
    "genre_ids": [10765],
    "original_language": "en",
    "original_name": "Snowpiercer",
    "origin_country": ["US"],
    "name": "Snowpiercer",
    "poster_path": "/95xQPSqwvQDRoB3rXUn4lRyJrBW.jpg",
    "backdrop_path": "/2fhU42I8pPdvEKfrZtuJ8KrzdeF.jpg",
    "vote_average": 7.4,
    "popularity": 311.105,
    "media_type": "tv"
  },
  {
    "video": false,
    "vote_average": 8.3,
    "overview":
        "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
    "release_date": "2020-12-25",
    "title": "Soul",
    "adult": false,
    "backdrop_path": "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
    "id": 508442,
    "genre_ids": [10751, 16, 35, 18, 10402, 14],
    "vote_count": 5486,
    "original_language": "en",
    "original_title": "Soul",
    "poster_path": "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
    "popularity": 738.359,
    "media_type": "movie"
  },
  {
    "vote_average": 8.3,
    "overview":
        "After encounters with a dragon and a princess on her own mission, a Dragon Knight becomes embroiled in events larger than he could have ever imagined.",
    "id": 118956,
    "vote_count": 22,
    "backdrop_path": "/ifGVUbvl36CnY9mp4kquK8In1Rh.jpg",
    "name": "DOTA: Dragon's Blood",
    "genre_ids": [10759, 16, 10765],
    "origin_country": ["US"],
    "original_language": "en",
    "original_name": "DOTA: Dragon's Blood",
    "poster_path": "/s1wP1YeQS9fgSHiXZ3yJb2ufB2D.jpg",
    "first_air_date": "2021-03-25",
    "popularity": 249.304,
    "media_type": "tv"
  },
  {
    "adult": false,
    "backdrop_path": "/abCn6fJjCPEZE3Q2dCmfidMxrEG.jpg",
    "genre_ids": [18, 53, 80],
    "id": 596161,
    "original_language": "en",
    "original_title": "Let Him Go",
    "overview":
        "Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.",
    "poster_path": "/EsLZoT8oHhQlGd1QpdbnvnwTzO.jpg",
    "release_date": "2020-11-05",
    "title": "Let Him Go",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 212,
    "popularity": 49.866,
    "media_type": "movie"
  }
];
