var popular = [
  {
    "release_date": "2021-03-18",
    "adult": false,
    "backdrop_path": "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
    "genre_ids": [28, 12, 14, 878],
    "vote_count": 4112,
    "original_language": "en",
    "original_title": "Zack Snyder's Justice League",
    "poster_path": "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    "title": "Zack Snyder's Justice League",
    "video": false,
    "vote_average": 8.6,
    "id": 791373,
    "overview":
        "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    "popularity": 8052.028,
    "media_type": "movie"
  },
  {
    "vote_average": 8.7,
    "overview":
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
    "vote_count": 3114,
    "poster_path": "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
    "first_air_date": "2013-04-07",
    "backdrop_path": "/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg",
    "name": "Attack on Titan",
    "genre_ids": [10765, 16, 10759],
    "id": 1429,
    "original_language": "ja",
    "original_name": "進撃の巨人",
    "origin_country": ["JP"],
    "popularity": 295.531,
    "media_type": "tv"
  },
  {
    "overview":
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
    "release_date": "2020-11-25",
    "id": 529203,
    "adult": false,
    "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
    "genre_ids": [10751, 14, 16, 35],
    "original_language": "en",
    "original_title": "The Croods: A New Age",
    "poster_path": "/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg",
    "title": "The Croods: A New Age",
    "video": false,
    "vote_average": 7.5,
    "vote_count": 1842,
    "popularity": 759.13,
    "media_type": "movie"
  },
  {
    "release_date": "2021-03-18",
    "adult": false,
    "backdrop_path": "/tzJZaglq1hR7RS35BKG68Xz7KY0.jpg",
    "genre_ids": [16, 35, 14],
    "vote_count": 40,
    "original_language": "ru",
    "original_title": "Ганзель, Гретель и Агентство Магии",
    "poster_path": "/4ZSzEDVdxWVMVO4oZDvoodQOEfr.jpg",
    "title": "Secret Magic Control Agency",
    "video": false,
    "vote_average": 7.7,
    "id": 797394,
    "overview":
        "The Secret Magic Control Agency sends its two best agents, Hansel and Gretel, to fight against the witch of the Gingerbread House.",
    "popularity": 67.939,
    "media_type": "movie"
  },
  {
    "adult": false,
    "backdrop_path": "/91nMJISKO8KqhTaYFMj6xFqI3GZ.jpg",
    "genre_ids": [18, 80, 9648, 53],
    "id": 567797,
    "original_language": "en",
    "original_title": "The Dry",
    "overview":
        "Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.",
    "poster_path": "/9tedVhYeK7fUqgwrjQAVw7RcI5d.jpg",
    "release_date": "2021-01-01",
    "title": "The Dry",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 10,
    "popularity": 4.091,
    "media_type": "movie"
  },
  {
    "genre_ids": [28, 35, 10751],
    "title": "Tom & Jerry",
    "original_language": "en",
    "original_title": "Tom & Jerry",
    "poster_path": "/6KErczPBROQty7QoIsaa6wJYXZi.jpg",
    "video": false,
    "vote_average": 7.4,
    "overview":
        "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
    "release_date": "2021-02-11",
    "vote_count": 1028,
    "id": 587807,
    "adult": false,
    "backdrop_path": "/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg",
    "popularity": 1681.653,
    "media_type": "movie"
  },
  {
    "overview":
        "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
    "id": 88396,
    "backdrop_path": "/JB17sIsU53NuWVUecOwrCA0CUp.jpg",
    "first_air_date": "2021-03-19",
    "vote_count": 2289,
    "original_language": "en",
    "vote_average": 7.8,
    "poster_path": "/qGA31gx01iIJMgk2MyVgurhCGeO.jpg",
    "original_name": "The Falcon and the Winter Soldier",
    "origin_country": ["US"],
    "name": "The Falcon and the Winter Soldier",
    "genre_ids": [10765, 10759, 18],
    "popularity": 3876.965,
    "media_type": "tv"
  },
  {
    "adult": false,
    "backdrop_path": "/tzm0qUH5fL01BtPazpksCtVaDcf.jpg",
    "genre_ids": [18],
    "id": 600354,
    "original_language": "en",
    "original_title": "The Father",
    "overview":
        "A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.",
    "poster_path": "/pr3bEQ517uMb5loLvjFQi8uLAsp.jpg",
    "release_date": "2020-12-23",
    "title": "The Father",
    "video": false,
    "vote_average": 8.2,
    "vote_count": 121,
    "popularity": 160.906,
    "media_type": "movie"
  }
];
