var season = [
  {
    "vote_average": 8.7,
    "overview":
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
    "vote_count": 3114,
    "poster_path": "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
    "first_air_date": "2013-04-07",
    "backdrop_path": "/yvKrycViRMQcIgdnjsM5JGNWU4Q.jpg",
    "name": "Attack on Titan",
    "genre_ids": [10765, 16, 10759],
    "id": 1429,
    "original_language": "ja",
    "original_name": "進撃の巨人",
    "origin_country": ["JP"],
    "popularity": 295.531,
    "media_type": "tv"
  },
  {
    "origin_country": ["US"],
    "name": "Game of Thrones",
    "genre_ids": [10765, 18, 10759],
    "backdrop_path": "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    "original_language": "en",
    "poster_path": "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    "id": 1399,
    "first_air_date": "2011-04-17",
    "vote_average": 8.4,
    "vote_count": 13694,
    "overview":
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    "original_name": "Game of Thrones",
    "popularity": 409.617,
    "media_type": "tv"
  },
  {
    "original_name": "Superman & Lois",
    "first_air_date": "2021-02-23",
    "genre_ids": [10759, 10765],
    "original_language": "en",
    "poster_path": "/6SJppowm7cdQgLkvoTlnTUSbjr9.jpg",
    "vote_count": 614,
    "name": "Superman & Lois",
    "id": 95057,
    "overview":
        "After years of facing megalomaniacal supervillains, monsters wreaking havoc on Metropolis, and alien invaders intent on wiping out the human race, The Man of Steel aka Clark Kent and Lois Lane come face to face with one of their greatest challenges ever: dealing with all the stress, pressures and complexities that come with being working parents in today's society.",
    "vote_average": 8.3,
    "origin_country": ["US"],
    "backdrop_path": "/gmbsR4SvYhhj4SvLAlTKxIkFxp9.jpg",
    "popularity": 914.336,
    "media_type": "tv"
  },
  {
    "vote_average": 8.1,
    "overview":
        "Hell-bent on exacting revenge and proving he was framed for his sister's murder, Álex sets out to unearth much more than the crime's real culprit.",
    "vote_count": 89,
    "name": "Who Killed Sara?",
    "first_air_date": "2021-03-24",
    "backdrop_path": "/pLG4ihU1d2XkQbASQDjsFu9U7d9.jpg",
    "id": 120168,
    "genre_ids": [18, 80, 9648],
    "original_language": "es",
    "original_name": "¿Quién mató a Sara?",
    "origin_country": ["MX"],
    "poster_path": "/o7uk5ChRt3quPIv8PcvPfzyXdMw.jpg",
    "popularity": 342.308,
    "media_type": "tv"
  },
  {
    "adult": false,
    "backdrop_path": "/91nMJISKO8KqhTaYFMj6xFqI3GZ.jpg",
    "genre_ids": [18, 80, 9648, 53],
    "id": 567797,
    "original_language": "en",
    "original_title": "The Dry",
    "overview":
        "Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.",
    "poster_path": "/9tedVhYeK7fUqgwrjQAVw7RcI5d.jpg",
    "release_date": "2021-01-01",
    "title": "The Dry",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 10,
    "popularity": 4.091,
    "media_type": "movie"
  },
  {
    "overview":
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
    "release_date": "2020-11-25",
    "id": 529203,
    "adult": false,
    "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
    "genre_ids": [10751, 14, 16, 35],
    "original_language": "en",
    "original_title": "The Croods: A New Age",
    "poster_path": "/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg",
    "title": "The Croods: A New Age",
    "video": false,
    "vote_average": 7.5,
    "vote_count": 1842,
    "popularity": 759.13,
    "media_type": "movie"
  },
  {
    "release_date": "2021-03-18",
    "adult": false,
    "backdrop_path": "/tzJZaglq1hR7RS35BKG68Xz7KY0.jpg",
    "genre_ids": [16, 35, 14],
    "vote_count": 40,
    "original_language": "ru",
    "original_title": "Ганзель, Гретель и Агентство Магии",
    "poster_path": "/4ZSzEDVdxWVMVO4oZDvoodQOEfr.jpg",
    "title": "Secret Magic Control Agency",
    "video": false,
    "vote_average": 7.7,
    "id": 797394,
    "overview":
        "The Secret Magic Control Agency sends its two best agents, Hansel and Gretel, to fight against the witch of the Gingerbread House.",
    "popularity": 67.939,
    "media_type": "movie"
  },
  {
    "name": "Supergirl",
    "backdrop_path": "/jgb9xICHFX8wTGQ75js4uNbttQs.jpg",
    "genre_ids": [18, 10765, 10759],
    "id": 62688,
    "original_language": "en",
    "poster_path": "/zsaiq8ZclPuneuN7loLEbsh1ANJ.jpg",
    "vote_count": 2877,
    "vote_average": 7.2,
    "original_name": "Supergirl",
    "origin_country": ["US"],
    "overview":
        "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    "first_air_date": "2015-10-26",
    "popularity": 214.249,
    "media_type": "tv"
  }
];
